quarkus.application.name=voice-stream-server

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:voice_stream}
quarkus.datasource.password=${DB_PASSWORD:voice_stream}
quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://localhost:5432/voice_stream}
quarkus.datasource.devservices.enabled=false

quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-migration-naming=true

quarkus.smallrye-graphql.ui.always-include=true
